PellTechnicalAssessment/Models/CustomerViewModel.cs
namespace PellTechnicalAssessment.Models;

public class CustomerViewModel
{
}

PellTechnicalAssessment/Models/ErrorViewModel.cs
namespace PellTechnicalAssessment.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
}

PellTechnicalAssessment/Controllers/ArtworkController.cs
using Microsoft.AspNetCore.Mvc;

namespace PellTechnicalAssessment.Controllers;
public class ArtworkController : Controller
{
    public IActionResult Index()
    {
        return this.View();
    }
}

PellTechnicalAssessment/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using PellTechnicalAssessment.Services;

namespace PellTechnicalAssessment.Controllers;

public class CustomerController : Controller
{
    private readonly CustomerService _customerService;

    public CustomerController(
        CustomerService customerService
        )
    {
        this._customerService = customerService;
    }

    public async Task<IActionResult> Index()
    {
        var customers = await this._customerService.GetAllCustomers();

        // TODO: view model

        return this.View();
    }
}

PellTechnicalAssessment/Controllers/ErrorController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PellTechnicalAssessment.Models;

namespace PellTechnicalAssessment.Controllers;

public class ErrorController : Controller
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Index()
    {
        return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
    }
}

PellTechnicalAssessment/Views/Artwork/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <button class="btn btn-primary" id="art-search">Load Art</button>

    <hr />

    <div class="row g-3" id="art-data">
    </div>
</div>
@section Scripts{
    <script src="~/js/artwork.js" asp-append-version="true"></script>
}

PellTechnicalAssessment/Views/Customer/Index.cshtml
@model CustomerViewModel

PellTechnicalAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PellTechnicalAssessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrop.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PellTechnicalAssessment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="Index">PellTechnicalAssessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artwork" asp-action="Index">Art</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>